# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/rgarc/OneDrive/Desktop/FPGA/projects/minessweeper_vga_testing/minsweeper_vga_testing/minsweeper_vga_testing.srcs/sources_1/ip/num_0/num_0.xci
# IP: The module: 'num_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rgarc/OneDrive/Desktop/FPGA/projects/minessweeper_vga_testing/minsweeper_vga_testing/minsweeper_vga_testing.gen/sources_1/ip/num_0/num_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'num_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/rgarc/OneDrive/Desktop/FPGA/projects/minessweeper_vga_testing/minsweeper_vga_testing/minsweeper_vga_testing.srcs/sources_1/ip/num_0/num_0.xci
# IP: The module: 'num_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rgarc/OneDrive/Desktop/FPGA/projects/minessweeper_vga_testing/minsweeper_vga_testing/minsweeper_vga_testing.gen/sources_1/ip/num_0/num_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'num_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
