# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/rgarc/OneDrive/Desktop/FPGA/projects/minessweeper_vga_testing/minsweeper_vga_testing/minsweeper_vga_testing.srcs/sources_1/ip/facing_down_bcm/facing_down_bcm.xci
# IP: The module: 'facing_down_bcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rgarc/OneDrive/Desktop/FPGA/projects/minessweeper_vga_testing/minsweeper_vga_testing/minsweeper_vga_testing.gen/sources_1/ip/facing_down_bcm_1/facing_down_bcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'facing_down_bcm'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/rgarc/OneDrive/Desktop/FPGA/projects/minessweeper_vga_testing/minsweeper_vga_testing/minsweeper_vga_testing.srcs/sources_1/ip/facing_down_bcm/facing_down_bcm.xci
# IP: The module: 'facing_down_bcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rgarc/OneDrive/Desktop/FPGA/projects/minessweeper_vga_testing/minsweeper_vga_testing/minsweeper_vga_testing.gen/sources_1/ip/facing_down_bcm_1/facing_down_bcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'facing_down_bcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
